# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-30 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0011_custom_motion_custom_supporters'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionversion',
            name='first_line_number',
            field=models.PositiveIntegerField(blank=False, default=1, null=True),
        ),
    ]
